train_dataset:
  glue:
    task: mnli
    tokenizer_name: bert-base-uncased
    split: train
    max_seq_length: 256
    shuffle: false
    drop_last: false
evaluators:
  - evaluator:
      label: glue_mnli
      eval_dataset:
        glue:
          task: mnli
          tokenizer_name: bert-base-uncased
          split: validation_matched
          max_seq_length: 256
          shuffle: false
          drop_last: false
      metric_names:
        - Accuracy
      summary:
        - max
  - evaluator+1:
      label: glue_mnli_mismatched
      eval_dataset:
        glue:
          task: mnli
          tokenizer_name: bert-base-uncased
          split: validation_mismatched
          max_seq_length: 256
          shuffle: false
          drop_last: false
      metric_names:
        - Accuracy
      summary:
        - max
model:
  bert_classification:
    num_labels: 3
    use_pretrained: true
    tokenizer_name: bert-base-uncased
    pretrained_model_name: bert-base-uncased
optimizer:
  decoupled_adamw:
    lr: 5.0e-5
    betas:
      - 0.9
      - 0.98
    eps: 1.0e-06
    weight_decay: 1.0e-6
schedulers:
  - linear_decay_with_warmup:
      t_warmup: 0.06dur
max_duration: 5ep
train_batch_size: 48
eval_batch_size: 48
seed: 19
device:
  gpu: {}
loggers:
  - progress_bar: {}
  - wandb: {}
  - object_store:
      object_store_hparams:
        provider: GOOGLE_STORAGE
        container: moin_bert_checkpoints
        key_environ: GCS_KEY
        secret_environ: GCS_SECRET
dataloader:
  pin_memory: true
  persistent_workers: true
  num_workers: 8
  timeout: 0
  prefetch_factor: 2
grad_accum: 1
precision: amp
grad_clip_norm: None
validate_every_n_batches: 2300
validate_every_n_epochs: 1
callbacks:
  - lr_monitor: {}
load_path: https://storage.googleapis.com/moin_bert_checkpoints/moin-bert-baseline/checkpoints/ep0-ba3500-rank0-wct2041 
load_weights_only: true
load_strict_model_weights: false
load_chunk_size: 8192
save_interval: 3500ba
save_artifact_name: '{run_name}/mnli/checkpoints/ep{epoch}-ba{batch}-rank{rank}'
save_folder: mnli_checkpoints
